# Generated by Django 5.2.3 on 2025-06-16 14:07

import django.core.validators
import exprep_tastyRecipes.profiles.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('first_name', models.CharField(max_length=30, validators=[exprep_tastyRecipes.profiles.validators.CapitalizeFirstNameValidator()])),
                ('last_name', models.CharField(max_length=30, validators=[exprep_tastyRecipes.profiles.validators.CapitalizeFirstNameValidator()])),
                ('chef', models.BooleanField(default=False)),
                ('bio', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
