# Generated by Django 5.2.3 on 2025-06-16 16:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(2, 'Nickname must be at least 2 chars long')]),
        ),
    ]
