# Generated by Django 5.2.1 on 2025-05-24 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='pets_numbers',
            new_name='pets_number',
        ),
    ]
